### ISSUE TITLE
Wrong license?

### ISSUE THREAD

**Issue by JoaquimLey** [Baseflow/FloatingNavigationView#3]
Shouldn't you be following the explicit LICENSE for the **original** project?

https://github.com/andremion/Floating-Navigation-View

Giving credit doesn't cost a thing.

**Comment by martijn00** [comment]
As you can see i follow the Apache license provided in the original project:
https://github.com/andremion/Floating-Navigation-View/blob/master/LICENSE
https://github.com/martijn00/FloatingNavigationView/blob/master/LICENSE

I also included a link to the original java project, and this is just a binding for it.
